# Generated by Django 5.2.1 on 2026-07-29 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_responsable_contacto_r003'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importacioncartola',
            name='procesada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importacioncartola',
            name='total_duplicadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importacioncartola',
            name='total_errores',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importacioncartola',
            name='total_filas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importacioncartola',
            name='total_importadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importacioncartola',
            name='total_validas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importacioncartola',
            name='validada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importacioncartola',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VALIDADA', 'Validada'), ('PROCESADA', 'Procesada'), ('CON_ERRORES', 'Con errores'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='PlantillaMapeoCartola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('formato_archivo', models.CharField(choices=[('CSV', 'CSV'), ('XLSX', 'Excel XLSX')], default='CSV', max_length=10)),
                ('nombre_hoja', models.CharField(blank=True, max_length=100)),
                ('fila_encabezado', models.PositiveIntegerField(default=1)),
                ('fila_inicio_datos', models.PositiveIntegerField(default=2)),
                ('separador_csv', models.CharField(default=';', max_length=5)),
                ('codificacion', models.CharField(default='utf-8-sig', max_length=30)),
                ('formato_fecha', models.CharField(default='%d/%m/%Y', max_length=30)),
                ('separador_decimal', models.CharField(default=',', max_length=1)),
                ('separador_miles', models.CharField(default='.', max_length=1)),
                ('ignorar_filas_vacias', models.BooleanField(default=True)),
                ('activa', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('observaciones', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantillas_cartola', to='administracion.banco')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('cuenta_bancaria', models.ForeignKey(blank=True, help_text='Opcional. Si se indica, tiene prioridad sobre la plantilla general del banco.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plantillas_cartola', to='administracion.cuentabancaria')),
            ],
            options={
                'verbose_name': 'Plantilla de mapeo de cartola',
                'verbose_name_plural': 'Plantillas de mapeo de cartola',
                'db_table': 'adm_plantilla_mapeo_cartola',
                'ordering': ['banco__nombre', 'nombre', '-version'],
            },
        ),
        migrations.AddField(
            model_name='importacioncartola',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='importaciones', to='administracion.plantillamapeocartola'),
        ),
        migrations.CreateModel(
            name='CampoMapeoCartola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('campo_destino', models.CharField(choices=[('FECHA_OPERACION', 'Fecha operación'), ('FECHA_CONTABLE', 'Fecha contable'), ('FECHA_VALOR', 'Fecha valor'), ('TIPO', 'Tipo de movimiento'), ('MONTO', 'Monto único'), ('MONTO_INGRESO', 'Monto ingreso'), ('MONTO_EGRESO', 'Monto egreso'), ('SALDO', 'Saldo'), ('DESCRIPCION', 'Descripción'), ('REFERENCIA', 'Referencia'), ('NUMERO_DOCUMENTO', 'Número documento'), ('IDENTIFICADOR_EXTERNO', 'Identificador externo'), ('CONTRAPARTE', 'Contraparte'), ('RUT_CONTRAPARTE', 'RUT contraparte'), ('CUENTA_CONTRAPARTE', 'Cuenta contraparte')], max_length=40)),
                ('columna_origen', models.CharField(max_length=150)),
                ('obligatorio', models.BooleanField(default=False)),
                ('valor_defecto', models.CharField(blank=True, max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='administracion.plantillamapeocartola')),
            ],
            options={
                'verbose_name': 'Campo de mapeo de cartola',
                'verbose_name_plural': 'Campos de mapeo de cartola',
                'db_table': 'adm_campo_mapeo_cartola',
                'ordering': ['orden', 'id'],
                'constraints': [models.UniqueConstraint(fields=('plantilla', 'campo_destino'), name='uniq_adm_campo_mapeo_plantilla_destino')],
            },
        ),
    ]
