# Generated by Django 5.2.1 on 2026-07-29 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_plantilla_mapeo_b004'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='clave_cartola_actualizada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banco',
            name='clave_cartola_cifrada',
            field=models.TextField(blank=True, help_text='Clave PDF de cartolas, cifrada. No se muestra en claro.'),
        ),
        migrations.AlterField(
            model_name='banco',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código interno o SBIF. Opcional; único si se informa.', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='banco',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo', ''), _negated=True), fields=('codigo',), name='uniq_adm_banco_codigo_no_vacio'),
        ),
    ]
