# Generated by Django 5.2.1 on 2026-07-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_banco_clave_cartola_b001'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='titular',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='nombre',
            field=models.CharField(help_text='Alias visible, p. ej. Cuenta corriente principal.', max_length=120),
        ),
    ]
