# Generated by Django 5.2.1 on 2026-07-29 21:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_cuenta_titular_b002'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importacioncartola',
            name='error_importacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='canal_movimiento',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='codigo_sucursal_movimiento',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='datos_originales',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='descripcion_movimiento',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='fecha_operacion_original',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='hora_operacion_original',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='monto_abono',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='monto_cargo',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='numero_fila_origen',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='numero_pagina_origen',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='sucursal_movimiento',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='tipo_movimiento',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='plantillamapeocartola',
            name='fecha_sin_anio',
            field=models.BooleanField(default=False, help_text='Si la cartola imprime solo día/mes (p. ej. Banco de Chile).'),
        ),
        migrations.AddField(
            model_name='plantillamapeocartola',
            name='identificador_saldo_final',
            field=models.CharField(blank=True, default='SALDO FINAL', max_length=80),
        ),
        migrations.AddField(
            model_name='plantillamapeocartola',
            name='identificador_saldo_inicial',
            field=models.CharField(blank=True, default='SALDO INICIAL', max_length=80),
        ),
        migrations.AddField(
            model_name='plantillamapeocartola',
            name='parser_codigo',
            field=models.CharField(choices=[('GENERICO', 'Genérico CSV/XLSX'), ('BANCO_ESTADO', 'Banco Estado / CuentaRUT PDF'), ('BANCO_FALABELLA', 'Banco Falabella PDF'), ('BANCO_CHILE', 'Banco de Chile PDF')], default='GENERICO', help_text='Parser PDF específico del banco, o genérico para CSV/XLSX.', max_length=30),
        ),
        migrations.AddField(
            model_name='plantillamapeocartola',
            name='simbolo_moneda',
            field=models.CharField(blank=True, default='$', max_length=5),
        ),
        migrations.AlterField(
            model_name='movimientobancario',
            name='monto',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='movimientobancario',
            name='saldo_bancario',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantillamapeocartola',
            name='formato_archivo',
            field=models.CharField(choices=[('CSV', 'CSV'), ('XLSX', 'Excel XLSX'), ('PDF', 'PDF bancario')], default='CSV', max_length=10),
        ),
        migrations.AlterField(
            model_name='plantillamapeocartola',
            name='separador_decimal',
            field=models.CharField(blank=True, default='', help_text='Vacío = montos enteros (sin decimales). Puntos se tratan como miles.', max_length=1),
        ),
        migrations.CreateModel(
            name='CartolaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=80)),
                ('tipo_cuenta_texto', models.CharField(blank=True, max_length=80)),
                ('numero_cartola', models.CharField(blank=True, max_length=40)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_inicio_periodo', models.DateField()),
                ('fecha_fin_periodo', models.DateField()),
                ('pagina_actual', models.PositiveIntegerField(blank=True, null=True)),
                ('total_paginas', models.PositiveIntegerField(blank=True, null=True)),
                ('referencia_documento', models.CharField(blank=True, max_length=120)),
                ('nombre_titular', models.CharField(blank=True, max_length=150)),
                ('tratamiento_titular', models.CharField(blank=True, max_length=40)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254)),
                ('numero_cuenta_texto', models.CharField(blank=True, max_length=50)),
                ('moneda', models.CharField(default='CLP', max_length=10)),
                ('sucursal_cuenta', models.CharField(blank=True, max_length=120)),
                ('codigo_sucursal_cuenta', models.CharField(blank=True, max_length=40)),
                ('ejecutivo_cuenta', models.CharField(blank=True, max_length=120)),
                ('telefono_banco', models.CharField(blank=True, max_length=40)),
                ('saldo_inicial', models.BigIntegerField(blank=True, null=True)),
                ('saldo_final', models.BigIntegerField(blank=True, null=True)),
                ('saldo_disponible', models.BigIntegerField(blank=True, null=True)),
                ('retenciones_total', models.BigIntegerField(blank=True, null=True)),
                ('retencion_un_dia', models.BigIntegerField(blank=True, null=True)),
                ('retencion_mas_un_dia', models.BigIntegerField(blank=True, null=True)),
                ('total_depositos', models.BigIntegerField(blank=True, null=True)),
                ('total_otros_abonos', models.BigIntegerField(blank=True, null=True)),
                ('total_abonos', models.BigIntegerField(blank=True, null=True)),
                ('total_cheques', models.BigIntegerField(blank=True, null=True)),
                ('total_giros', models.BigIntegerField(blank=True, null=True)),
                ('total_giros_autoservicio', models.BigIntegerField(blank=True, null=True)),
                ('total_redcompra', models.BigIntegerField(blank=True, null=True)),
                ('total_comisiones', models.BigIntegerField(blank=True, null=True)),
                ('total_impuestos', models.BigIntegerField(blank=True, null=True)),
                ('total_otros_cargos', models.BigIntegerField(blank=True, null=True)),
                ('total_cargos', models.BigIntegerField(blank=True, null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('cuenta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartolas', to='administracion.cuentabancaria')),
                ('importacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartola', to='administracion.importacioncartola')),
            ],
            options={
                'verbose_name': 'Cartola bancaria',
                'verbose_name_plural': 'Cartolas bancarias',
                'db_table': 'adm_cartola_bancaria',
                'ordering': ['-fecha_fin_periodo', '-id'],
            },
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='cartola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='administracion.cartolabancaria'),
        ),
    ]
