# Generated by Django 5.2.1 on 2026-07-29 22:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_cartola_movimientos_enteros_b003'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionMovimientoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.CharField(choices=[('PAGO_CLIENTE', 'Pago de cliente'), ('ANTICIPO_FACTORING', 'Anticipo de factoring'), ('LIQUIDACION_FACTORING', 'Liquidación de factoring'), ('DEVOLUCION_RESPONSABLE', 'Devolución de responsable'), ('TRANSFERENCIA_INTERNA', 'Transferencia interna'), ('OTRO_INGRESO', 'Otro ingreso'), ('ENTREGA_FONDO', 'Entrega de fondo'), ('REEMBOLSO_RENDICION', 'Reembolso de rendición'), ('DEVOLUCION_CLIENTE', 'Devolución a cliente'), ('COMISION_FACTORING', 'Comisión de factoring'), ('COBRO_RECURSO', 'Cobro de recurso'), ('GASTO_BANCARIO', 'Gasto bancario'), ('OTRO_EGRESO', 'Otro egreso')], max_length=40)),
                ('contraparte_normalizada', models.CharField(blank=True, max_length=200)),
                ('rut_contraparte_normalizado', models.CharField(blank=True, max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('origen', models.CharField(choices=[('MANUAL', 'Manual')], default='MANUAL', max_length=20)),
                ('clasificado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('clasificacion_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclasificaciones', to='administracion.clasificacionmovimientobancario')),
                ('clasificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clasificaciones_movimiento', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clasificaciones', to='administracion.movimientobancario')),
            ],
            options={
                'verbose_name': 'Clasificación de movimiento bancario',
                'verbose_name_plural': 'Clasificaciones de movimientos bancarios',
                'db_table': 'adm_clasificacion_movimiento_bancario',
                'ordering': ['-clasificado_en', '-id'],
                'indexes': [models.Index(fields=['categoria'], name='adm_clasifi_categor_f35602_idx'), models.Index(fields=['activa'], name='adm_clasifi_activa_70c7cc_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('movimiento',), name='uniq_adm_clasificacion_activa')],
            },
        ),
    ]
