# Generated by Django 5.2.1 on 2026-08-16 00:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EjecucionMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciada_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('finalizada_en', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CURSO', 'En curso'), ('COMPLETADA', 'Completada'), ('PARCIAL', 'Completada parcialmente'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('plataforma', models.CharField(blank=True, help_text='Linux, Windows, etc.', max_length=255)),
                ('version_python', models.CharField(blank=True, max_length=50)),
                ('errores', models.JSONField(blank=True, default=list)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'esp_ejecucion_medicion',
                'ordering': ['-iniciada_en'],
            },
        ),
        migrations.CreateModel(
            name='OperacionMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EXPORTAR_ARCHIVOS', 'Exportar archivos'), ('ARCHIVAR_ARCHIVOS', 'Archivar archivos'), ('ELIMINAR_TEMPORALES', 'Eliminar archivos temporales'), ('HISTORIZAR_BD', 'Historizar registros'), ('DEPURAR_BD', 'Depurar registros'), ('OTRO', 'Otro')], max_length=30)),
                ('estado', models.CharField(choices=[('PREPARADA', 'Preparada'), ('EN_CURSO', 'En curso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('ERROR', 'Error')], default='PREPARADA', max_length=20)),
                ('tipo_objetivo', models.CharField(blank=True, help_text='RUTA, TABLA, TEMPORALES, etc.', max_length=50)),
                ('identificador_objetivo', models.CharField(blank=True, help_text='Ruta, nombre de tabla u otro identificador textual.', max_length=1000)),
                ('criterios', models.JSONField(blank=True, default=dict, help_text='Ejemplo: fecha_hasta, extensiones, antigüedad, filtros.')),
                ('usuario', models.CharField(blank=True, help_text='Nombre/username informativo. No es FK para mantener la independencia de la app.', max_length=150)),
                ('bytes_estimados', models.PositiveBigIntegerField(default=0)),
                ('bytes_liberados', models.PositiveBigIntegerField(default=0)),
                ('registros_afectados', models.PositiveBigIntegerField(default=0)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('iniciada_en', models.DateTimeField(blank=True, null=True)),
                ('finalizada_en', models.DateTimeField(blank=True, null=True)),
                ('resultado', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'esp_operacion_mantenimiento',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='RutaMonitoreada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('ruta', models.CharField(help_text='Ruta relativa a BASE_DIR o ruta absoluta, según relativa_a_base_dir.', max_length=500)),
                ('relativa_a_base_dir', models.BooleanField(default=True, help_text='Si está activo, la ruta se resolverá respecto de BASE_DIR.')),
                ('categoria', models.CharField(choices=[('DATOS_NEGOCIO', 'Datos de negocio'), ('MEDIA', 'Media / archivos subidos'), ('TEMPORAL', 'Archivos temporales'), ('BACKUP', 'Respaldos'), ('REGENERABLE', 'Archivos regenerables'), ('APLICACION', 'Aplicación / sistema'), ('DOCUMENTACION', 'Documentación'), ('OTRO', 'Otro')], default='OTRO', max_length=30)),
                ('recursiva', models.BooleanField(default=True, help_text='Analizar también subdirectorios.')),
                ('seguir_enlaces_simbolicos', models.BooleanField(default=False, help_text='Normalmente debe permanecer desactivado para evitar recorridos fuera del proyecto o ciclos.')),
                ('patrones_incluir', models.JSONField(blank=True, default=list, help_text='Patrones opcionales. Ejemplo: ["*.pdf", "*.jpg"]. Vacío significa incluir todos.')),
                ('patrones_excluir', models.JSONField(blank=True, default=list, help_text='Patrones opcionales. Ejemplo: ["*.tmp", "__pycache__"].')),
                ('activa', models.BooleanField(default=True)),
                ('visible_dashboard', models.BooleanField(default=True, help_text='Mostrar esta ruta en el dashboard principal.')),
                ('permite_mantenimiento', models.BooleanField(default=False, help_text='Indica si posteriormente podrán ofrecerse acciones de archivado/depuración sobre esta ruta.')),
                ('observaciones', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'esp_ruta_monitoreada',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UmbralAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_objetivo', models.CharField(choices=[('DISCO', 'Disco'), ('RUTA', 'Ruta'), ('BASE_DATOS', 'Base de datos'), ('TABLA', 'Tabla')], max_length=20)),
                ('identificador', models.CharField(blank=True, help_text='Ejemplo: /, intervenciones, default, adm_factura_venta.', max_length=500)),
                ('metrica', models.CharField(help_text='Ejemplo: porcentaje_usado, total_bytes, total_registros.', max_length=100)),
                ('operador', models.CharField(choices=[('GTE', 'Mayor o igual'), ('LTE', 'Menor o igual'), ('GT', 'Mayor'), ('LT', 'Menor')], default='GTE', max_length=5)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unidad', models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('BYTES', 'Bytes'), ('ARCHIVOS', 'Cantidad de archivos'), ('REGISTROS', 'Cantidad de registros')], max_length=20)),
                ('nivel', models.CharField(choices=[('INFORMATIVO', 'Informativo'), ('ADVERTENCIA', 'Advertencia'), ('CRITICO', 'Crítico')], default='ADVERTENCIA', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'esp_umbral_alerta',
                'ordering': ['tipo_objetivo', 'nivel', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MedicionBaseDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(default='default', max_length=100)),
                ('vendor', models.CharField(blank=True, help_text='sqlite, postgresql, mysql, etc.', max_length=50)),
                ('engine', models.CharField(blank=True, max_length=255)),
                ('nombre_base_datos', models.CharField(blank=True, max_length=500)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('puerto', models.CharField(blank=True, max_length=20)),
                ('total_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('total_tablas', models.PositiveIntegerField(default=0)),
                ('total_registros', models.PositiveBigIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bases_datos', to='espaciometro.ejecucionmedicion')),
            ],
            options={
                'db_table': 'esp_medicion_bd',
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='MedicionDisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punto_montaje', models.CharField(default='/', max_length=500)),
                ('dispositivo', models.CharField(blank=True, max_length=255)),
                ('sistema_archivos', models.CharField(blank=True, max_length=100)),
                ('total_bytes', models.PositiveBigIntegerField(default=0)),
                ('usados_bytes', models.PositiveBigIntegerField(default=0)),
                ('libres_bytes', models.PositiveBigIntegerField(default=0)),
                ('porcentaje_usado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discos', to='espaciometro.ejecucionmedicion')),
            ],
            options={
                'db_table': 'esp_medicion_disco',
                'ordering': ['punto_montaje'],
            },
        ),
        migrations.CreateModel(
            name='MedicionRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_resuelta', models.CharField(blank=True, max_length=1000)),
                ('total_bytes', models.PositiveBigIntegerField(default=0)),
                ('total_archivos', models.PositiveBigIntegerField(default=0)),
                ('total_directorios', models.PositiveBigIntegerField(default=0)),
                ('total_enlaces_simbolicos', models.PositiveBigIntegerField(default=0)),
                ('total_imagenes', models.PositiveBigIntegerField(default=0)),
                ('total_pdf', models.PositiveBigIntegerField(default=0)),
                ('total_documentos', models.PositiveBigIntegerField(default=0)),
                ('total_planillas', models.PositiveBigIntegerField(default=0)),
                ('total_videos', models.PositiveBigIntegerField(default=0)),
                ('total_comprimidos', models.PositiveBigIntegerField(default=0)),
                ('total_temporales', models.PositiveBigIntegerField(default=0)),
                ('total_otros', models.PositiveBigIntegerField(default=0)),
                ('archivo_mas_antiguo_fecha', models.DateTimeField(blank=True, null=True)),
                ('archivo_mas_antiguo_ruta', models.CharField(blank=True, max_length=1000)),
                ('archivo_mas_reciente_fecha', models.DateTimeField(blank=True, null=True)),
                ('archivo_mas_reciente_ruta', models.CharField(blank=True, max_length=1000)),
                ('archivo_mas_grande_bytes', models.PositiveBigIntegerField(default=0)),
                ('archivo_mas_grande_ruta', models.CharField(blank=True, max_length=1000)),
                ('archivos_inaccesibles', models.PositiveBigIntegerField(default=0)),
                ('duracion_ms', models.PositiveBigIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='espaciometro.ejecucionmedicion')),
                ('ruta_monitoreada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mediciones', to='espaciometro.rutamonitoreada')),
            ],
            options={
                'db_table': 'esp_medicion_ruta',
                'ordering': ['-ejecucion__iniciada_en', 'ruta_monitoreada__nombre'],
            },
        ),
        migrations.CreateModel(
            name='MedicionTabla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esquema', models.CharField(blank=True, max_length=120)),
                ('nombre_tabla', models.CharField(max_length=255)),
                ('total_registros', models.PositiveBigIntegerField(blank=True, null=True)),
                ('datos_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('indices_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('total_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('medicion_bd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tablas', to='espaciometro.medicionbasedatos')),
            ],
            options={
                'db_table': 'esp_medicion_tabla',
                'ordering': ['-total_bytes', 'nombre_tabla'],
            },
        ),
        migrations.CreateModel(
            name='ResumenTipoArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('IMAGEN', 'Imagen'), ('PDF', 'PDF'), ('DOCUMENTO', 'Documento'), ('PLANILLA', 'Planilla'), ('VIDEO', 'Video'), ('COMPRIMIDO', 'Comprimido'), ('TEMPORAL', 'Temporal'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('extension', models.CharField(blank=True, help_text='Ejemplo: .jpg, .pdf, .xlsx', max_length=30)),
                ('cantidad', models.PositiveBigIntegerField(default=0)),
                ('total_bytes', models.PositiveBigIntegerField(default=0)),
                ('archivo_mas_antiguo_fecha', models.DateTimeField(blank=True, null=True)),
                ('archivo_mas_reciente_fecha', models.DateTimeField(blank=True, null=True)),
                ('medicion_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_archivo', to='espaciometro.medicionruta')),
            ],
            options={
                'db_table': 'esp_resumen_tipo_archivo',
                'ordering': ['-total_bytes'],
            },
        ),
        migrations.AddConstraint(
            model_name='medicionbasedatos',
            constraint=models.UniqueConstraint(fields=('ejecucion', 'alias'), name='uq_esp_med_bd'),
        ),
        migrations.AddConstraint(
            model_name='mediciondisco',
            constraint=models.UniqueConstraint(fields=('ejecucion', 'punto_montaje'), name='uq_esp_med_disco'),
        ),
        migrations.AddIndex(
            model_name='mediciontabla',
            index=models.Index(fields=['nombre_tabla'], name='esp_medicio_nombre__57069e_idx'),
        ),
        migrations.AddIndex(
            model_name='mediciontabla',
            index=models.Index(fields=['total_registros'], name='esp_medicio_total_r_886b03_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediciontabla',
            constraint=models.UniqueConstraint(fields=('medicion_bd', 'esquema', 'nombre_tabla'), name='uq_esp_med_tabla'),
        ),
        migrations.AddConstraint(
            model_name='resumentipoarchivo',
            constraint=models.UniqueConstraint(fields=('medicion_ruta', 'categoria', 'extension'), name='uq_esp_tipo_archivo'),
        ),
        migrations.AddIndex(
            model_name='medicionruta',
            index=models.Index(fields=['total_bytes'], name='esp_medicio_total_b_28173f_idx'),
        ),
        migrations.AddIndex(
            model_name='medicionruta',
            index=models.Index(fields=['total_archivos'], name='esp_medicio_total_a_deb3f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicionruta',
            constraint=models.UniqueConstraint(fields=('ejecucion', 'ruta_monitoreada'), name='uq_esp_med_ruta'),
        ),
    ]
