# Generated by Django 5.2.1 on 2026-08-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaciometro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutamonitoreada',
            name='extensiones_interes',
            field=models.JSONField(blank=True, default=list, help_text='Extensiones específicas que requieren monitorización especial.'),
        ),
        migrations.AddField(
            model_name='rutamonitoreada',
            name='tipos_interes',
            field=models.JSONField(blank=True, default=list, help_text='Categorías de archivo que requieren monitorización especial.'),
        ),
    ]
