# Generated by Django 5.2.1 on 2026-08-17 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaciometro', '0002_rutamonitoreada_extensiones_interes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteCandidatosMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('creado_por', models.CharField(blank=True, max_length=150)),
                ('filtros', models.JSONField(blank=True, default=dict)),
                ('total_archivos', models.PositiveIntegerField(default=0)),
                ('total_bytes', models.PositiveBigIntegerField(default=0)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('PREPARADO', 'Preparado para respaldo'), ('CANCELADO', 'Cancelado')], default='ABIERTO', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'esp_lote_candidatos_mantenimiento',
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CandidatoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_relativa', models.TextField()),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(blank=True, max_length=40)),
                ('extension', models.CharField(blank=True, max_length=40)),
                ('total_bytes_snapshot', models.PositiveBigIntegerField()),
                ('mtime_ns_snapshot', models.BigIntegerField()),
                ('inode_snapshot', models.PositiveBigIntegerField(default=0)),
                ('dispositivo_snapshot', models.PositiveBigIntegerField(default=0)),
                ('modificado_snapshot', models.DateTimeField(blank=True, null=True)),
                ('tipo_interes_snapshot', models.BooleanField(default=False)),
                ('extension_interes_snapshot', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ruta_monitoreada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatos_mantenimiento', to='espaciometro.rutamonitoreada')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='espaciometro.lotecandidatosmantenimiento')),
            ],
            options={
                'db_table': 'esp_candidato_mantenimiento',
                'ordering': ['ruta_monitoreada__nombre', 'ruta_relativa'],
                'constraints': [models.UniqueConstraint(fields=('lote', 'ruta_monitoreada', 'ruta_relativa'), name='esp_unique_candidato_lote_ruta')],
            },
        ),
    ]
