# Generated by Django 5.2.1 on 2026-08-17 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaciometro', '0003_lotecandidatosmantenimiento_candidatomantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespaldoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PREPARANDO', 'Preparando'), ('LISTO', 'Listo'), ('PARCIAL', 'Parcial'), ('ERROR', 'Error')], default='PREPARANDO', max_length=20)),
                ('creado_por', models.CharField(blank=True, max_length=150)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255)),
                ('ruta_relativa_archivo', models.TextField(blank=True)),
                ('total_candidatos', models.PositiveIntegerField(default=0)),
                ('incluidos', models.PositiveIntegerField(default=0)),
                ('omitidos', models.PositiveIntegerField(default=0)),
                ('total_bytes_contenido', models.PositiveBigIntegerField(default=0)),
                ('total_bytes_paquete', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('errores', models.JSONField(blank=True, default=list)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respaldos', to='espaciometro.lotecandidatosmantenimiento')),
            ],
            options={
                'db_table': 'esp_respaldo_mantenimiento',
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleRespaldoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('INCLUIDO', 'Incluido'), ('OMITIDO', 'Omitido')], max_length=20)),
                ('estado_validacion', models.CharField(blank=True, max_length=30)),
                ('motivo', models.TextField(blank=True)),
                ('ruta_zip', models.TextField(blank=True)),
                ('total_bytes', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_respaldo', to='espaciometro.candidatomantenimiento')),
                ('respaldo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='espaciometro.respaldomantenimiento')),
            ],
            options={
                'db_table': 'esp_detalle_respaldo_mantenimiento',
                'ordering': ['candidato__ruta_monitoreada__nombre', 'candidato__ruta_relativa'],
                'constraints': [models.UniqueConstraint(fields=('respaldo', 'candidato'), name='esp_unique_detalle_respaldo_candidato')],
            },
        ),
    ]
