# Generated by Django 5.2.1 on 2026-08-17 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaciometro', '0004_respaldomantenimiento_detallerespaldomantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDescargaRespaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(choices=[('INICIADA', 'Entrega iniciada'), ('CONFIRMADA', 'Recepción confirmada'), ('VERIFICADA', 'Recepción verificada'), ('VERIFICACION_FALLIDA', 'Verificación fallida'), ('ERROR', 'Error')], default='INICIADA', max_length=30)),
                ('sha256_esperado', models.CharField(blank=True, max_length=64)),
                ('sha256_servidor', models.CharField(blank=True, max_length=64)),
                ('sha256_cliente', models.CharField(blank=True, max_length=64)),
                ('total_bytes', models.PositiveBigIntegerField(default=0)),
                ('ip_cliente', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.TextField(blank=True)),
                ('detalle', models.TextField(blank=True)),
                ('iniciada_en', models.DateTimeField(auto_now_add=True)),
                ('confirmada_en', models.DateTimeField(blank=True, null=True)),
                ('respaldo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descargas', to='espaciometro.respaldomantenimiento')),
            ],
            options={
                'db_table': 'esp_registro_descarga_respaldo',
                'ordering': ['-iniciada_en', '-id'],
            },
        ),
    ]
