# Generated by Django 5.2.1 on 2026-08-17 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaciometro', '0005_registrodescargarespaldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotecandidatosmantenimiento',
            name='estado',
            field=models.CharField(choices=[('ABIERTO', 'Abierto'), ('PREPARADO', 'Preparado para respaldo'), ('LIBERANDO', 'Liberación en curso'), ('LIBERADO', 'Liberado'), ('LIBERACION_PARCIAL', 'Liberación parcial'), ('CANCELADO', 'Cancelado')], default='ABIERTO', max_length=20),
        ),
        migrations.CreateModel(
            name='LiberacionMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EJECUTANDO', 'Ejecutando'), ('COMPLETADA', 'Completada'), ('PARCIAL', 'Parcial'), ('ERROR', 'Error')], default='EJECUTANDO', max_length=20)),
                ('usuario', models.CharField(blank=True, max_length=150)),
                ('total_candidatos', models.PositiveIntegerField(default=0)),
                ('liberados', models.PositiveIntegerField(default=0)),
                ('omitidos', models.PositiveIntegerField(default=0)),
                ('total_bytes_objetivo', models.PositiveBigIntegerField(default=0)),
                ('total_bytes_liberados', models.PositiveBigIntegerField(default=0)),
                ('confirmacion', models.CharField(blank=True, max_length=100)),
                ('errores', models.JSONField(blank=True, default=list)),
                ('iniciado_en', models.DateTimeField(auto_now_add=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('descarga_verificada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liberaciones', to='espaciometro.registrodescargarespaldo')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liberaciones', to='espaciometro.lotecandidatosmantenimiento')),
                ('respaldo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liberaciones', to='espaciometro.respaldomantenimiento')),
            ],
            options={
                'db_table': 'esp_liberacion_mantenimiento',
                'ordering': ['-iniciado_en', '-id'],
                'permissions': [('puede_liberar_archivos', 'Puede liberar archivos mediante Espaciómetro')],
            },
        ),
        migrations.CreateModel(
            name='DetalleLiberacionMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('LIBERADO', 'Liberado'), ('OMITIDO', 'Omitido'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('ruta_relativa', models.TextField()),
                ('total_bytes_snapshot', models.PositiveBigIntegerField(default=0)),
                ('motivo', models.TextField(blank=True)),
                ('liberado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_liberacion', to='espaciometro.candidatomantenimiento')),
                ('liberacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='espaciometro.liberacionmantenimiento')),
            ],
            options={
                'db_table': 'esp_detalle_liberacion_mantenimiento',
                'ordering': ['candidato__ruta_monitoreada__nombre', 'ruta_relativa'],
                'constraints': [models.UniqueConstraint(fields=('liberacion', 'candidato'), name='esp_unique_liberacion_candidato')],
            },
        ),
    ]
