# Generated by Django 5.2.1 on 2026-08-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaciometro', '0006_alter_lotecandidatosmantenimiento_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotecandidatosmantenimiento',
            name='estado',
            field=models.CharField(choices=[('ABIERTO', 'Abierto'), ('PREPARADO', 'Preparado para liberación'), ('LIBERANDO', 'Liberación en curso'), ('LIBERADO', 'Liberado'), ('LIBERACION_PARCIAL', 'Liberación parcial'), ('CANCELADO', 'Cancelado')], default='ABIERTO', max_length=20),
        ),
    ]
