# Generated by Django 5.2.1 on 2026-08-17 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaciometro', '0007_alter_lotecandidatosmantenimiento_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetiroRespaldoServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EJECUTANDO', 'Ejecutando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='EJECUTANDO', max_length=20)),
                ('usuario', models.CharField(blank=True, max_length=150)),
                ('nombre_archivo_snapshot', models.CharField(blank=True, max_length=255)),
                ('total_bytes_snapshot', models.PositiveBigIntegerField(default=0)),
                ('sha256_snapshot', models.CharField(blank=True, max_length=64)),
                ('confirmacion', models.CharField(blank=True, max_length=100)),
                ('detalle', models.TextField(blank=True)),
                ('errores', models.JSONField(blank=True, default=list)),
                ('iniciado_en', models.DateTimeField(auto_now_add=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('descarga_verificada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retiros_respaldo_servidor', to='espaciometro.registrodescargarespaldo')),
                ('liberacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retiros_respaldo_servidor', to='espaciometro.liberacionmantenimiento')),
                ('respaldo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retiros_servidor', to='espaciometro.respaldomantenimiento')),
            ],
            options={
                'db_table': 'esp_retiro_respaldo_servidor',
                'ordering': ['-iniciado_en', '-id'],
            },
        ),
    ]
