# Generated by Django 5.2.1 on 2026-08-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaciometro', '0008_retirorespaldoservidor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespaldoBaseDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor', models.CharField(max_length=50)),
                ('nombre_base', models.CharField(max_length=255)),
                ('formato', models.CharField(choices=[('SQLITE_SQL', 'SQLite SQL'), ('POSTGRES_CUSTOM', 'PostgreSQL custom')], max_length=30)),
                ('estado', models.CharField(choices=[('VERIFICADO', 'Verificado'), ('ERROR', 'Error')], default='ERROR', max_length=20)),
                ('usuario', models.CharField(blank=True, max_length=150)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255)),
                ('ruta_relativa', models.TextField(blank=True)),
                ('total_bytes', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('detalle', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('verificado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'esp_respaldo_base_datos',
                'ordering': ['-creado_en', '-id'],
                'permissions': [('puede_gestionar_respaldos_bd', 'Puede crear y descargar respaldos manuales de base de datos')],
            },
        ),
    ]
