"""
Factories de prueba (esqueleto A / R021 / B021 / F014 / X013).

Cuando se implemente un corte vertical, añadir factories aquí
(p. ej. con factory_boy o helpers simples) para datos repetibles.
"""


# TODO(R021): def make_responsable(**kwargs): ...
# TODO(R021): def make_rendicion_borrador(**kwargs): ...
# TODO(B021): def make_cuenta_bancaria(**kwargs): ...
# TODO(F014): def make_factura_venta(**kwargs): ...
# TODO(X013): def make_operacion_factoring(**kwargs): ...
