# Generated by Django 5.2.1 on 2025-05-27 01:20

import django.db.models.deletion
import django.utils.timezone
import extintores.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(blank=True, max_length=100)),
                ('correo', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=150)),
                ('comuna', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('contacto', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOdt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('costo_materiales', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('agente', models.CharField(choices=[('PQS_40%', 'PQS_40%'), ('PQS_75%', 'PQS_75%'), ('PQS_90%', 'PQS_90%'), ('CO2', 'CO2'), ('AGUA', 'AGUA'), ('ACETATO_POTASIO', 'ACETATO_POTASIO'), ('ESPUMA_MECANICA', 'ESPUMA_MECANICA'), ('otro', 'otro')], max_length=100)),
                ('nro_precinto', models.IntegerField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('sello_incen', models.CharField(blank=True, default='S/I', max_length=150)),
                ('sello_incen_ste', models.CharField(blank=True, default='S/I', max_length=50)),
                ('certificado', models.CharField(blank=True, default='S/I', max_length=50)),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('fuera_servicio', 'Fuera de Servicio'), ('pendiente', 'Pendiente')], max_length=50)),
                ('exterior', models.BooleanField(default=True)),
                ('ph_ultima', models.DateField(blank=True, null=True)),
                ('ph_estado', models.CharField(choices=[('al_dia', 'Al día'), ('vencido_5_co2', 'Vencido +5 años CO2'), ('vencido_12_pqs', 'Vencido +12 años PQS')], max_length=50)),
                ('ph_vencimiento', models.DateField(blank=True, null=True)),
                ('valvula', models.BooleanField(default=True)),
                ('manometro', models.BooleanField(default=True)),
                ('manguera', models.BooleanField(default=True)),
                ('cintillo', models.BooleanField(default=True)),
                ('agente_extintor', models.BooleanField(default=True)),
                ('tubo_sifon', models.BooleanField(default=True)),
                ('sellos_seguro', models.BooleanField(default=True)),
                ('seguridad', models.BooleanField(default=True)),
                ('rotulacion', models.BooleanField(default=True)),
                ('ultima_fecha', models.DateField(blank=True, null=True)),
                ('recarga', models.BooleanField(default=True)),
                ('mantencion', models.BooleanField(default=True)),
                ('presion', models.CharField(choices=[('195', '195 PSI'), ('150', '150 PSI'), ('650', '650 PSI'), ('850', '850 PSI')], max_length=50)),
                ('peso', models.CharField(choices=[('1 kg', '1 kg'), ('2 kg', '2 kg'), ('4 Kg', '4 Kg'), ('6 Kg', '6 Kg'), ('10 Kg', '10 Kg'), ('25 Kg', '25 Kg'), ('50 Kg', '50 Kg'), ('100 Kg', '100 Kg')], max_length=50)),
                ('correcta', models.BooleanField(default=True)),
                ('acceso', models.BooleanField(default=True)),
                ('instrucciones', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('componentes_relacionados', models.ManyToManyField(blank=True, to='extintores.categoriaproducto')),
            ],
        ),
        migrations.CreateModel(
            name='CompatibilidadProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('detalle_odt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extintores.detalleodt')),
            ],
        ),
        migrations.CreateModel(
            name='Intervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('revision', 'Revisión'), ('mantencion', 'Mantención'), ('recarga', 'Recarga')], max_length=20)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('odt', models.IntegerField(blank=True, null=True)),
                ('con_odt', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extintores.cliente')),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='intervenciones')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenIntervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen1', models.ImageField(blank=True, upload_to=extintores.utils.upload_path, verbose_name='Imagen1')),
                ('imagen2', models.ImageField(blank=True, upload_to=extintores.utils.upload_path, verbose_name='Imagen2')),
                ('imagen3', models.ImageField(blank=True, upload_to=extintores.utils.upload_path, verbose_name='Imagen3')),
                ('imagen4', models.ImageField(blank=True, upload_to=extintores.utils.upload_path, verbose_name='Imagen4')),
                ('imagen5', models.ImageField(blank=True, upload_to=extintores.utils.upload_path, verbose_name='Imagen5')),
                ('imagen6', models.ImageField(blank=True, upload_to=extintores.utils.upload_path, verbose_name='Imagen6')),
                ('intervencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='extintores.intervencion')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleIntervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente', models.CharField(choices=[('PQS_40%', 'PQS_40%'), ('PQS_75%', 'PQS_75%'), ('PQS_90%', 'PQS_90%'), ('CO2', 'CO2'), ('AGUA', 'AGUA'), ('ACETATO_POTASIO', 'ACETATO_POTASIO'), ('ESPUMA_MECANICA', 'ESPUMA_MECANICA'), ('otro', 'otro')], max_length=100)),
                ('nro_precinto', models.IntegerField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('sello_incen', models.CharField(blank=True, default='S/I', max_length=150)),
                ('sello_incen_ste', models.CharField(blank=True, default='S/I', max_length=50)),
                ('certificado', models.CharField(blank=True, default='S/I', max_length=50)),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('fuera_servicio', 'Fuera de Servicio'), ('pendiente', 'Pendiente')], max_length=50)),
                ('exterior', models.BooleanField(default=True)),
                ('ph_ultima', models.DateField(blank=True, null=True)),
                ('ph_estado', models.CharField(blank=True, max_length=50, null=True)),
                ('ph_vencimiento', models.DateField(blank=True, null=True)),
                ('valvula', models.BooleanField(default=True)),
                ('manometro', models.BooleanField(default=True)),
                ('manguera', models.BooleanField(default=True)),
                ('cintillo', models.BooleanField(default=True)),
                ('agente_extintor', models.BooleanField(default=True)),
                ('tubo_sifon', models.BooleanField(default=True)),
                ('sellos_seguro', models.BooleanField(default=True)),
                ('seguridad', models.BooleanField(default=True)),
                ('rotulacion', models.BooleanField(default=True)),
                ('ultima_fecha', models.DateField(blank=True, null=True)),
                ('recarga', models.BooleanField(default=True)),
                ('mantencion', models.BooleanField(default=True)),
                ('presion', models.CharField(choices=[('195', '195 PSI'), ('150', '150 PSI'), ('650', '650 PSI'), ('850', '850 PSI')], max_length=50)),
                ('peso', models.CharField(choices=[('1 kg', '1 kg'), ('2 kg', '2 kg'), ('4 Kg', '4 Kg'), ('6 Kg', '6 Kg'), ('10 Kg', '10 Kg'), ('25 Kg', '25 Kg'), ('50 Kg', '50 Kg'), ('100 Kg', '100 Kg')], max_length=50)),
                ('correcta', models.BooleanField(default=True)),
                ('acceso', models.BooleanField(default=True)),
                ('instrucciones', models.BooleanField(default=True)),
                ('intervencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='extintores.intervencion')),
            ],
        ),
        migrations.CreateModel(
            name='Odt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estatus', models.BooleanField(default=False)),
                ('intervencion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odt_rel', to='extintores.intervencion')),
            ],
        ),
        migrations.AddField(
            model_name='detalleodt',
            name='odt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='extintores.odt'),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='extintores.categoriaproducto')),
                ('compatibilidad', models.ManyToManyField(through='extintores.CompatibilidadProducto', to='extintores.detalleodt')),
            ],
        ),
        migrations.CreateModel(
            name='ItemOdt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('odt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='extintores.odt')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extintores.producto')),
            ],
        ),
        migrations.AddField(
            model_name='compatibilidadproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extintores.producto'),
        ),
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_id', models.CharField(blank=True, max_length=50, verbose_name='N° Identificación Profesional')),
                ('specialization', models.CharField(blank=True, max_length=100, verbose_name='Especialidad')),
                ('hire_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Contratación')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='tecnicos/firmas/', verbose_name='Firma Electrónica')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
