# Generated by Django 5.2.1 on 2025-05-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extintores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleodt',
            name='ph_estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
