# Generated by Django 5.2.1 on 2025-06-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extintores', '0004_bitacora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleintervencion',
            name='agente',
            field=models.CharField(blank=True, choices=[('PQS_40%', 'PQS_40%'), ('PQS_75%', 'PQS_75%'), ('PQS_90%', 'PQS_90%'), ('CO2', 'CO2'), ('AGUA', 'AGUA'), ('ACETATO_POTASIO', 'ACETATO_POTASIO'), ('ESPUMA_MECANICA', 'ESPUMA_MECANICA'), ('otro', 'otro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='detalleintervencion',
            name='estado',
            field=models.CharField(blank=True, choices=[('operativo', 'Operativo'), ('fuera_servicio', 'Fuera de Servicio'), ('pendiente', 'Pendiente')], max_length=50),
        ),
        migrations.AlterField(
            model_name='detalleintervencion',
            name='peso',
            field=models.CharField(blank=True, choices=[('1 kg', '1 kg'), ('2 kg', '2 kg'), ('4 Kg', '4 Kg'), ('6 Kg', '6 Kg'), ('10 Kg', '10 Kg'), ('25 Kg', '25 Kg'), ('50 Kg', '50 Kg'), ('100 Kg', '100 Kg')], max_length=50),
        ),
        migrations.AlterField(
            model_name='detalleintervencion',
            name='presion',
            field=models.CharField(blank=True, choices=[('195', '195 PSI'), ('150', '150 PSI'), ('650', '650 PSI'), ('850', '850 PSI')], max_length=50),
        ),
    ]
