# Generated by Django 5.2.1 on 2025-06-04 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extintores', '0005_alter_detalleintervencion_agente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre']},
        ),
    ]
