# Generated by Django 5.2.1 on 2025-06-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extintores', '0006_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleintervencion',
            name='agente',
            field=models.CharField(blank=True, choices=[('PQS_40%', 'PQS_40%'), ('PQS_75%', 'PQS_75%'), ('PQS_90%', 'PQS_90%'), ('CO2', 'CO2'), ('AGUA', 'AGUA'), ('Tipo K', 'Tipo K'), ('AFFF 3%', 'AFFF 3%'), ('otro', 'otro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='detalleodt',
            name='agente',
            field=models.CharField(choices=[('PQS_40%', 'PQS_40%'), ('PQS_75%', 'PQS_75%'), ('PQS_90%', 'PQS_90%'), ('CO2', 'CO2'), ('AGUA', 'AGUA'), ('Tipo K', 'Tipo K'), ('AFFF 3%', 'AFFF 3%'), ('otro', 'otro')], max_length=100),
        ),
    ]
