# Generated by Django 5.2.1 on 2025-06-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extintores', '0007_alter_detalleintervencion_agente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleintervencion',
            name='baja_por_oxido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detalleintervencion',
            name='baja_por_ph',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detalleintervencion',
            name='habilitado_un_ano',
            field=models.BooleanField(default=False),
        ),
    ]
