# Generated by Django 5.2.1 on 2025-06-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extintores', '0008_detalleintervencion_baja_por_oxido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianprofile',
            name='rut',
            field=models.CharField(blank=True, max_length=50, verbose_name='Rut'),
        ),
        migrations.AlterField(
            model_name='detalleintervencion',
            name='peso',
            field=models.CharField(blank=True, choices=[('1 kg', '1 kg'), ('2 kg', '2 kg'), ('3 kg', '3 kg'), ('4 Kg', '4 Kg'), ('5 Kg', '5 Kg'), ('6 Kg', '6 Kg'), ('10 Kg', '10 Kg'), ('25 Kg', '25 Kg'), ('50 Kg', '50 Kg'), ('100 Kg', '100 Kg'), ('6 Lt', '6 Lt'), ('10 Lt', '10 Lt'), ('25 Lt', '25 Lt'), ('50 Lt', '50 Lt')], max_length=50),
        ),
        migrations.AlterField(
            model_name='detalleodt',
            name='peso',
            field=models.CharField(choices=[('1 kg', '1 kg'), ('2 kg', '2 kg'), ('3 kg', '3 kg'), ('4 Kg', '4 Kg'), ('5 Kg', '5 Kg'), ('6 Kg', '6 Kg'), ('10 Kg', '10 Kg'), ('25 Kg', '25 Kg'), ('50 Kg', '50 Kg'), ('100 Kg', '100 Kg'), ('6 Lt', '6 Lt'), ('10 Lt', '10 Lt'), ('25 Lt', '25 Lt'), ('50 Lt', '50 Lt')], max_length=50),
        ),
    ]
