# Generated by Django 5.2.1 on 2025-06-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extintores', '0009_technicianprofile_rut_alter_detalleintervencion_peso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleintervencion',
            name='baja_por_fuera_norma',
            field=models.BooleanField(default=False),
        ),
    ]
