# Generated by Django 5.2.1 on 2025-06-09 21:26

import extintores.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extintores', '0010_detalleintervencion_baja_por_fuera_norma'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenintervencion',
            name='imagen7',
            field=models.ImageField(blank=True, null=True, upload_to=extintores.utils.upload_path, verbose_name='Imagen7'),
        ),
        migrations.AddField(
            model_name='imagenintervencion',
            name='imagen8',
            field=models.ImageField(blank=True, null=True, upload_to=extintores.utils.upload_path, verbose_name='Imagen8'),
        ),
        migrations.AddField(
            model_name='imagenintervencion',
            name='imagen9',
            field=models.ImageField(blank=True, null=True, upload_to=extintores.utils.upload_path, verbose_name='Imagen9'),
        ),
        migrations.AlterField(
            model_name='detalleintervencion',
            name='estado',
            field=models.CharField(blank=True, choices=[('operativo', 'Operativo'), ('f/servicio', 'Fuera/Servicio'), ('pendiente', 'Pendiente')], max_length=50),
        ),
        migrations.AlterField(
            model_name='detalleodt',
            name='estado',
            field=models.CharField(choices=[('operativo', 'Operativo'), ('f/servicio', 'Fuera/Servicio'), ('pendiente', 'Pendiente')], max_length=50),
        ),
        migrations.AlterField(
            model_name='imagenintervencion',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to=extintores.utils.upload_path, verbose_name='Imagen1'),
        ),
        migrations.AlterField(
            model_name='imagenintervencion',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to=extintores.utils.upload_path, verbose_name='Imagen2'),
        ),
        migrations.AlterField(
            model_name='imagenintervencion',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to=extintores.utils.upload_path, verbose_name='Imagen3'),
        ),
        migrations.AlterField(
            model_name='imagenintervencion',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to=extintores.utils.upload_path, verbose_name='Imagen4'),
        ),
        migrations.AlterField(
            model_name='imagenintervencion',
            name='imagen5',
            field=models.ImageField(blank=True, null=True, upload_to=extintores.utils.upload_path, verbose_name='Imagen5'),
        ),
        migrations.AlterField(
            model_name='imagenintervencion',
            name='imagen6',
            field=models.ImageField(blank=True, null=True, upload_to=extintores.utils.upload_path, verbose_name='Imagen6'),
        ),
    ]
