# Generated by Django 5.2.1 on 2025-06-10 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extintores', '0011_imagenintervencion_imagen7_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intervencion',
            name='alias',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='intervencion',
            name='tecnico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervenciones', to=settings.AUTH_USER_MODEL, verbose_name='Técnico'),
        ),
    ]
