# Generated by Django 5.2.1 on 2025-06-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extintores', '0012_intervencion_alias_alter_intervencion_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleintervencion',
            name='estado',
            field=models.CharField(blank=True, choices=[('operativo', 'Operativo'), ('f/servicio', 'Fuera/Servicio'), ('baja/oxido', 'Baja/Oxido'), ('baja/f/nor.', 'Baja/F/Norma'), ('extin./abo.', 'Extintor/Abollado'), ('pendiente', 'Pendiente'), ('otro', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='detalleodt',
            name='estado',
            field=models.CharField(choices=[('operativo', 'Operativo'), ('f/servicio', 'Fuera/Servicio'), ('baja/oxido', 'Baja/Oxido'), ('baja/f/nor.', 'Baja/F/Norma'), ('extin./abo.', 'Extintor/Abollado'), ('pendiente', 'Pendiente'), ('otro', 'Otro')], max_length=50),
        ),
    ]
