# Generated by Django 5.2.1 on 2025-06-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extintores', '0013_alter_detalleintervencion_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleintervencion',
            name='baja_otro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detalleintervencion',
            name='extintor_abollado',
            field=models.BooleanField(default=False),
        ),
    ]
