# Generated by Django 5.2.1 on 2025-06-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extintores', '0014_detalleintervencion_baja_otro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervencion',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalleintervencion',
            name='estado',
            field=models.CharField(blank=True, choices=[('operativo', 'Operativo'), ('f/servicio', 'Fuera/Servicio'), ('f/de/norma', 'Fuera/de/Norma'), ('baja/oxido', 'Baja/Oxido'), ('extin./abo.', 'Extintor/Abollado'), ('habili.+1', 'habilitado +1 año'), ('nuevo', 'Nuevo'), ('pendiente', 'Pendiente'), ('otro', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='detalleodt',
            name='estado',
            field=models.CharField(choices=[('operativo', 'Operativo'), ('f/servicio', 'Fuera/Servicio'), ('f/de/norma', 'Fuera/de/Norma'), ('baja/oxido', 'Baja/Oxido'), ('extin./abo.', 'Extintor/Abollado'), ('habili.+1', 'habilitado +1 año'), ('nuevo', 'Nuevo'), ('pendiente', 'Pendiente'), ('otro', 'Otro')], max_length=50),
        ),
    ]
