# Generated by Django 5.2.1 on 2025-06-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extintores', '0015_intervencion_notas_alter_detalleintervencion_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleintervencion',
            name='extintor_nuevo',
            field=models.BooleanField(default=False),
        ),
    ]
