# Generated by Django 5.2.1 on 2025-06-17 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extintores', '0016_detalleintervencion_extintor_nuevo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemodt',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemodt',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FactorAjusteCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extintores.categoriaproducto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extintores.cliente')),
            ],
        ),
    ]
