# Generated by Django 5.2.1 on 2025-07-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extintores', '0020_alter_detalleintervencion_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleintervencion',
            name='agente',
            field=models.CharField(blank=True, choices=[('PQS_40%', 'PQS_40%'), ('PQS_50%', 'PQS_50%'), ('PQS_55%', 'PQS_55%'), ('PQS_70%', 'PQS_70%'), ('PQS_75%', 'PQS_75%'), ('PQS_90%', 'PQS_90%'), ('CO2', 'CO2'), ('AGUA', 'AGUA'), ('Tipo K', 'Tipo K'), ('AFFF 3%', 'AFFF 3%'), ('CF302 6%', 'CF302 6%'), ('CF302 10%', 'CF302 10%'), ('otro', 'otro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='detalleintervencion',
            name='presion',
            field=models.CharField(blank=True, choices=[('120', '120 PSI'), ('195', '195 PSI'), ('150', '150 PSI'), ('650', '650 PSI'), ('850', '850 PSI'), ('250', '250 BAR')], max_length=50),
        ),
        migrations.AlterField(
            model_name='detalleodt',
            name='agente',
            field=models.CharField(choices=[('PQS_40%', 'PQS_40%'), ('PQS_50%', 'PQS_50%'), ('PQS_55%', 'PQS_55%'), ('PQS_70%', 'PQS_70%'), ('PQS_75%', 'PQS_75%'), ('PQS_90%', 'PQS_90%'), ('CO2', 'CO2'), ('AGUA', 'AGUA'), ('Tipo K', 'Tipo K'), ('AFFF 3%', 'AFFF 3%'), ('CF302 6%', 'CF302 6%'), ('CF302 10%', 'CF302 10%'), ('otro', 'otro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='detalleodt',
            name='presion',
            field=models.CharField(choices=[('120', '120 PSI'), ('195', '195 PSI'), ('150', '150 PSI'), ('650', '650 PSI'), ('850', '850 PSI'), ('250', '250 BAR')], max_length=50),
        ),
        migrations.AlterField(
            model_name='intervencion',
            name='tipo',
            field=models.CharField(choices=[('revision', 'Revisión'), ('mantencion', 'Mantención'), ('recarga', 'Recarga'), ('venta', 'Venta')], max_length=20),
        ),
    ]
