# Generated by Django 5.2.1 on 2025-07-15 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extintores', '0021_alter_detalleintervencion_agente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='detalleodt',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='odt',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DetalleIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extintores.producto')),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='extintores.ingresostock')),
            ],
        ),
    ]
