# Generated by Django 5.2.1 on 2025-07-15 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extintores', '0022_ingresostock_remove_detalleodt_observaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleodt',
            name='costo_materiales',
        ),
    ]
