# Generated by Django 5.2.1 on 2025-08-01 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extintores', '0023_remove_detalleodt_costo_materiales'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticaDetalleExtintor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=7)),
                ('tipo_intervencion', models.CharField(max_length=20)),
                ('agente', models.CharField(max_length=50)),
                ('peso', models.CharField(max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extintores.cliente')),
            ],
            options={
                'unique_together': {('id', 'mes', 'tipo_intervencion', 'agente', 'peso', 'cliente')},
            },
        ),
        migrations.CreateModel(
            name='EstadisticaDetalleProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=7)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nombre', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extintores.cliente')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='extintores.producto')),
            ],
            options={
                'unique_together': {('mes', 'producto', 'cliente')},
            },
        ),
        migrations.CreateModel(
            name='EstadisticaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=7)),
                ('tipo', models.CharField(max_length=30)),
                ('cantidad_intervenciones', models.PositiveIntegerField(default=0)),
                ('cantidad_extintores', models.PositiveIntegerField(default=0)),
                ('tipo_intervencion', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad_odt', models.PositiveIntegerField(default=0)),
                ('total_productos_utilizados', models.PositiveIntegerField(default=0)),
                ('total_valor_productos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('categoria_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extintores.categoriaproducto')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extintores.cliente')),
            ],
            options={
                'unique_together': {('id', 'mes', 'tipo', 'cliente', 'categoria_producto', 'tipo_intervencion')},
            },
        ),
    ]
