# Generated by Django 5.2.1 on 2025-09-02 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extintores', '0024_estadisticadetalleextintor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_ultima_intervencion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultima_intervencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ultimo_servicio_cliente', to='extintores.intervencion'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultimo_alias',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
