# Generated by Django 5.2.1 on 2025-09-21 19:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extintores', '0025_cliente_fecha_ultima_intervencion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('alias', models.CharField(max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_servicios', to='extintores.cliente')),
                ('intervencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='extintores.intervencion')),
            ],
        ),
    ]
