# Generated by Django 5.2.1 on 2025-09-21 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extintores', '0026_historialservicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemIntervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('intervencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='extintores.intervencion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extintores.producto')),
            ],
        ),
    ]
