# Generated by Django 5.2.1 on 2026-08-30 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extintores', '0027_itemintervencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odt',
            name='intervencion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odt_rel', to='extintores.intervencion'),
        ),
    ]
