# Generated by Django 5.2.1 on 2026-08-30 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extintores', '0028_alter_odt_intervencion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intervencion',
            options={'permissions': [('manage_users', 'Puede gestionar usuarios y roles'), ('manage_permissions', 'Puede gestionar permisos'), ('sign_documents', 'Puede firmar documentos de intervenciones'), ('view_financial_data', 'Puede ver datos financieros')]},
        ),
    ]
