# Generated by Django 5.2.1 on 2026-08-30 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extintores', '0029_alter_intervencion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intervencion',
            options={'permissions': [('manage_users', 'Puede gestionar usuarios y roles'), ('manage_permissions', 'Puede gestionar permisos'), ('sign_documents', 'Puede firmar documentos de intervenciones'), ('view_financial_data', 'Puede ver datos financieros'), ('view_operations', 'Puede consultar operaciones'), ('manage_operations', 'Puede modificar operaciones'), ('manage_catalog', 'Puede modificar clientes y catalogo'), ('manage_inventory', 'Puede modificar inventario'), ('view_reports', 'Puede consultar reportes y exportaciones')]},
        ),
    ]
