# Generated by Django 5.2.1 on 2026-08-30 03:08

import django.db.models.deletion
import extintores.models
from django.conf import settings
from django.db import migrations, models


def migrar_imagenes_legacy(apps, schema_editor):
    ImagenLegacy = apps.get_model('extintores', 'ImagenIntervencion')
    ImagenServicio = apps.get_model('extintores', 'ImagenServicio')
    campos = [f'imagen{i}' for i in range(1, 10)]
    nuevos = []
    for legacy in ImagenLegacy.objects.all().iterator():
        for orden, campo in enumerate(campos, start=1):
            nombre = getattr(legacy, campo)
            if nombre:
                nuevos.append(ImagenServicio(
                    intervencion_id=legacy.intervencion_id,
                    archivo=nombre,
                    orden=orden,
                ))
    ImagenServicio.objects.bulk_create(nuevos, batch_size=500)


def revertir_imagenes_legacy(apps, schema_editor):
    ImagenServicio = apps.get_model('extintores', 'ImagenServicio')
    ImagenServicio.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('extintores', '0030_alter_intervencion_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to=extintores.models.imagen_servicio_upload_path)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('intervencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_nuevas', to='extintores.intervencion')),
                ('usuario_carga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('orden', 'id'),
            },
        ),
        migrations.RunPython(migrar_imagenes_legacy, revertir_imagenes_legacy),
    ]
