# Generated by Django 5.2.1 on 2026-09-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extintores', '0031_imagenservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='datos_anteriores',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='datos_nuevos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='metadatos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='metodo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='resultado',
            field=models.CharField(db_index=True, default='exito', max_length=20),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='accion',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='modelo',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
