"""Selectores de lectura para facturación y cobranza (F003–F004, F011–F013)."""

# TODO(F003): def listar_facturas(filtros) -> QuerySet: ...
# TODO(F004): def estado_cobranza_factura(factura_id) -> dict: ...
# TODO(F012): def antiguedad_saldos(...) -> list: ...
# TODO(F013): def exportar_facturas(...) -> ...: ...
