"""Selectores de lectura para factoring (X001–X002, X012)."""

# TODO(X001): def listar_empresas_factoring(...) -> QuerySet: ...
# TODO(X002): def listar_operaciones_factoring(filtros) -> QuerySet: ...
# TODO(X012): def reportes_factoring(...) -> dict: ...
