"""
X001–X013 — Factoring.

Modelos base: EmpresaFactoring, OperacionFactoring,
EventoFactoring, FlujoFactoring.
Se entrelaza con facturas, pagos y movimientos bancarios.
"""

# TODO(X002): def crear_operacion_factoring(...): ...
# TODO(X003): def registrar_evento_factoring(...): ...
# TODO(X004): def registrar_flujo_anticipo(...): ...
# TODO(X005): def confirmar_pago_factor(...): ...
# TODO(X007): def iniciar_cobro_con_recurso(...): ...
# TODO(X008): def detectar_pago_directo_factura_cedida(...): ...
# TODO(X009): def devolver_pago_cliente_factoring(...): ...
# TODO(X010): def conciliar_devolucion_factoring(...): ...
# TODO(X011): def conciliar_liquidacion_factor(...): ...
