"""
F001–F014 — Facturación, pagos y cobranza.

Modelos base: FacturaVenta, PagoCliente, AplicacionPagoFactura,
DevolucionPagoCliente, GestionCobranza, AlertaCobranza.
Cliente reutiliza ``extintores.Cliente``.
"""

# TODO(F002): def registrar_factura(...): ...
# TODO(F004): def recalcular_estado_cobranza(...): ...
# TODO(F005): def registrar_pago_cliente(...): ...
# TODO(F006): def aplicar_pago_a_facturas(...): ...
# TODO(F008): def gestionar_excedente(...): ...
# TODO(F009): def vincular_pago_con_cartola(...): ...
# TODO(F010): def registrar_gestion_cobranza(...): ...
